// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/DBN-DEV/pingcc/domain"
	mock "github.com/stretchr/testify/mock"
)

// PingTaskRepo is an autogenerated mock type for the PingTaskRepo type
type PingTaskRepo struct {
	mock.Mock
}

type PingTaskRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *PingTaskRepo) EXPECT() *PingTaskRepo_Expecter {
	return &PingTaskRepo_Expecter{mock: &_m.Mock}
}

// Find provides a mock function with given fields: ctx, uid
func (_m *PingTaskRepo) Find(ctx context.Context, uid uint64) (*domain.PingTask, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *domain.PingTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*domain.PingTask, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *domain.PingTask); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.PingTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PingTaskRepo_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type PingTaskRepo_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - uid uint64
func (_e *PingTaskRepo_Expecter) Find(ctx interface{}, uid interface{}) *PingTaskRepo_Find_Call {
	return &PingTaskRepo_Find_Call{Call: _e.mock.On("Find", ctx, uid)}
}

func (_c *PingTaskRepo_Find_Call) Run(run func(ctx context.Context, uid uint64)) *PingTaskRepo_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *PingTaskRepo_Find_Call) Return(_a0 *domain.PingTask, _a1 error) *PingTaskRepo_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PingTaskRepo_Find_Call) RunAndReturn(run func(context.Context, uint64) (*domain.PingTask, error)) *PingTaskRepo_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByAgentID provides a mock function with given fields: ctx, agentUID
func (_m *PingTaskRepo) FindByAgentID(ctx context.Context, agentUID uint64) ([]domain.PingTask, error) {
	ret := _m.Called(ctx, agentUID)

	if len(ret) == 0 {
		panic("no return value specified for FindByAgentID")
	}

	var r0 []domain.PingTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]domain.PingTask, error)); ok {
		return rf(ctx, agentUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []domain.PingTask); ok {
		r0 = rf(ctx, agentUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.PingTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, agentUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// PingTaskRepo_FindByAgentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAgentID'
type PingTaskRepo_FindByAgentID_Call struct {
	*mock.Call
}

// FindByAgentID is a helper method to define mock.On call
//   - ctx context.Context
//   - agentUID uint64
func (_e *PingTaskRepo_Expecter) FindByAgentID(ctx interface{}, agentUID interface{}) *PingTaskRepo_FindByAgentID_Call {
	return &PingTaskRepo_FindByAgentID_Call{Call: _e.mock.On("FindByAgentID", ctx, agentUID)}
}

func (_c *PingTaskRepo_FindByAgentID_Call) Run(run func(ctx context.Context, agentUID uint64)) *PingTaskRepo_FindByAgentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *PingTaskRepo_FindByAgentID_Call) Return(_a0 []domain.PingTask, _a1 error) *PingTaskRepo_FindByAgentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *PingTaskRepo_FindByAgentID_Call) RunAndReturn(run func(context.Context, uint64) ([]domain.PingTask, error)) *PingTaskRepo_FindByAgentID_Call {
	_c.Call.Return(run)
	return _c
}

// NewPingTaskRepo creates a new instance of PingTaskRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPingTaskRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *PingTaskRepo {
	mock := &PingTaskRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
