// Code generated by mockery v2.43.2. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/DBN-DEV/pingcc/domain"
	mock "github.com/stretchr/testify/mock"
)

// TcpPingTaskRepo is an autogenerated mock type for the TcpPingTaskRepo type
type TcpPingTaskRepo struct {
	mock.Mock
}

type TcpPingTaskRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *TcpPingTaskRepo) EXPECT() *TcpPingTaskRepo_Expecter {
	return &TcpPingTaskRepo_Expecter{mock: &_m.Mock}
}

// Find provides a mock function with given fields: ctx, uid
func (_m *TcpPingTaskRepo) Find(ctx context.Context, uid uint64) (*domain.TcpPingTask, error) {
	ret := _m.Called(ctx, uid)

	if len(ret) == 0 {
		panic("no return value specified for Find")
	}

	var r0 *domain.TcpPingTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) (*domain.TcpPingTask, error)); ok {
		return rf(ctx, uid)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) *domain.TcpPingTask); ok {
		r0 = rf(ctx, uid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.TcpPingTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, uid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TcpPingTaskRepo_Find_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Find'
type TcpPingTaskRepo_Find_Call struct {
	*mock.Call
}

// Find is a helper method to define mock.On call
//   - ctx context.Context
//   - uid uint64
func (_e *TcpPingTaskRepo_Expecter) Find(ctx interface{}, uid interface{}) *TcpPingTaskRepo_Find_Call {
	return &TcpPingTaskRepo_Find_Call{Call: _e.mock.On("Find", ctx, uid)}
}

func (_c *TcpPingTaskRepo_Find_Call) Run(run func(ctx context.Context, uid uint64)) *TcpPingTaskRepo_Find_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *TcpPingTaskRepo_Find_Call) Return(_a0 *domain.TcpPingTask, _a1 error) *TcpPingTaskRepo_Find_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TcpPingTaskRepo_Find_Call) RunAndReturn(run func(context.Context, uint64) (*domain.TcpPingTask, error)) *TcpPingTaskRepo_Find_Call {
	_c.Call.Return(run)
	return _c
}

// FindByAgentID provides a mock function with given fields: ctx, agentUID
func (_m *TcpPingTaskRepo) FindByAgentID(ctx context.Context, agentUID uint64) ([]domain.TcpPingTask, error) {
	ret := _m.Called(ctx, agentUID)

	if len(ret) == 0 {
		panic("no return value specified for FindByAgentID")
	}

	var r0 []domain.TcpPingTask
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint64) ([]domain.TcpPingTask, error)); ok {
		return rf(ctx, agentUID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint64) []domain.TcpPingTask); ok {
		r0 = rf(ctx, agentUID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.TcpPingTask)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint64) error); ok {
		r1 = rf(ctx, agentUID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TcpPingTaskRepo_FindByAgentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByAgentID'
type TcpPingTaskRepo_FindByAgentID_Call struct {
	*mock.Call
}

// FindByAgentID is a helper method to define mock.On call
//   - ctx context.Context
//   - agentUID uint64
func (_e *TcpPingTaskRepo_Expecter) FindByAgentID(ctx interface{}, agentUID interface{}) *TcpPingTaskRepo_FindByAgentID_Call {
	return &TcpPingTaskRepo_FindByAgentID_Call{Call: _e.mock.On("FindByAgentID", ctx, agentUID)}
}

func (_c *TcpPingTaskRepo_FindByAgentID_Call) Run(run func(ctx context.Context, agentUID uint64)) *TcpPingTaskRepo_FindByAgentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uint64))
	})
	return _c
}

func (_c *TcpPingTaskRepo_FindByAgentID_Call) Return(_a0 []domain.TcpPingTask, _a1 error) *TcpPingTaskRepo_FindByAgentID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TcpPingTaskRepo_FindByAgentID_Call) RunAndReturn(run func(context.Context, uint64) ([]domain.TcpPingTask, error)) *TcpPingTaskRepo_FindByAgentID_Call {
	_c.Call.Return(run)
	return _c
}

// NewTcpPingTaskRepo creates a new instance of TcpPingTaskRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTcpPingTaskRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *TcpPingTaskRepo {
	mock := &TcpPingTaskRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
