name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  GO_VERSION: 1.18

jobs:
  golangci-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          # stable: 'false'  # Keep this line to be able to use rc and beta version of Go (ex: 1.18.0-rc1).
          go-version: ${{ env.GO_VERSION }}
      - name: Install Protoc
        uses: arduino/setup-protoc@v2
      - name: Gen pb.go
        run: make gen
      - name: lint
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          version: latest
          # skip cache because of flaky behaviors
          skip-build-cache: true
          skip-pkg-cache: true